//=================== GENERAL ===================

export interface InvoiceResponse<T> {
  code: number;
  message: string;
  data: T;
}

//=================== TOKEN ===================
export interface ReqToken {
  userName: String;
  password: String;
}

export interface RespToken {
  token: string;
}

//=================== GENERATE INVOICE ===================

export interface CreatePaymentDTO {
  business_code: string;
  transaction_number: string;
  pay_order_number: string;
  operation_number: string;
  city_code: string;
  city_name: string;
  town_code: string;
  town_name: string;
  entity_code: string;
  entity_name: string;
  agency_code: string;
  agency_name: string;
  operator_code: string;
  operator_username: string;
  payer_business_name: string;
  payer_business_nit: string;
  payer_ci: string;
  payer_name: string;
  payer_phone: string;
  payer_email: string;
  currency_symbol: string;
  exchange_rate: string;
  way_pay: string;
  note: string;
  items: ItemComputarizada[];
}

export interface ItemComputarizada {
  quantity: string;
  concept: string;
  unit_price: string;
}
// Generated by https://quicktype.io

export interface RespInvoiceCreatePayment {
  documents: Document[];
}

export interface Document {
  type: string;
  title: string;
  emitter_short_name: string;
  emitter_name: string;
  central_branch_number: string;
  central_branch_name: string;
  central_branch_address: string;
  central_branch_phone: string;
  central_branch_municipality: string;
  central_branch_department: string;
  central_branch_country: string;
  other_branch_number: null;
  other_branch_name: null;
  other_branch_address: null;
  other_branch_phone: null;
  other_branch_municipality: null;
  other_branch_department: null;
  other_branch_country: null;
  emitter_nit: string;
  transmitter_nit: string;
  transmitter_message: string;
  invoice_number: number;
  authorization_number: string;
  economic_activity: string;
  date: Date;
  receiver_name: string;
  receiver_nit: string;
  currency: string;
  total_amount: string;
  tax_total_amount: string;
  literal_total_amount: string;
  control_code: string;
  qr: string;
  general_legend: string;
  law_legend: string;
  clarifying_legend: string;
  thanks_legend: string;
  deadline_date: string;
  items: Item[];
  authorization_id: string;
}

export interface Item {
  concept: string;
  specification: string;
  quantity: string;
  unit_price: string;
  tax_unit_price: string;
  amount: string;
  tax_amount: string;
}

//=================== INVOICE FILE ===================
export interface Req_InvoiceFile {
  business_code: String;
  transaction_number: String;
}

//=================== INVOICE JSON ===================
export interface Req_InvoiceJSON {
  business_code: String;
  transaction_number: String;
}

//=================== CANCEL INVOICE JSON ===================

export interface Req_CancelInvoice {
  business_code: string;
  transaction_number: string;
  city_code: string;
  city_name: string;
  town_code: string;
  town_name: string;
  entity_code: string;
  entity_name: string;
  agency_code: string;
  agency_name: string;
  operator_code: string;
  operator_username: string;
  note: string;
}

export interface Resp_CancelInvoice {
  code: number;
  message: string;
}
