import {
  BillingData,
  Infotransaction,
  ItemsToPay,
  PayerInfo,
} from '../../general/geneneralDTO';

// Generated by https://quicktype.io
export interface ContractPostPago {
  IdDeudaPostPago: string;
  NroContrato: string;
  Periodo: string;
  TotalServicio: number;
  TotalOtrosServicios: number;
  TotalOperadores: number;
  TotalIntereses: number;
  TotalDeudaPostpago: number;
}
export interface Resp_ContractPostPago {}

// DEBTS POST-PAGO
export interface Req_DebtPostPago {
  NroContrato: number;
}
export interface Resp_DebtPostPago {
  code: string;
  name: string;
  description: string;
  amount: number;
  currency: string;
  extraData?: string;
  period?: string;
}

export interface DebtPostPago {
  IdDeudaPostPago: string;
  NroContrato: string;
  Periodo: string;
  FacturaServicio: FacturaServicio;
  FacturasOtrosServicios: any[];
  FacturasOperadores: any[];
  TotalServicio: number;
  TotalOtrosServicios: number;
  TotalOperadores: number;
  TotalIntereses: number;
  TotalDeudaPostpago: number;
}

export interface FacturaServicio {
  NroFactura: string;
  Periodo: string;
  Contrato: string;
  Cliente: Cliente;
  FechaEmision: Date;
  NroAutotizacion: string;
  NroFacturaSin: string;
  FechaLimite: Date;
  CodigoControl: string;
  Qr: string;
  Modalidad: string;
  Detalle: Detalle[];
  TotalServicio: number;
  TotalCreditoFiscal: number;
  TotalInteres: number;
}

export interface Cliente {
  CodigoCliente: number;
  NombreCompleto: string;
  CiNit: string;
}

export interface Detalle {
  NroFactura: string;
  CodigoItem: string;
  DescripcionItem: string;
  MontoTotal: number;
  MontoCreditoFiscal: number;
}

export interface ExtraDebtPostPago {
  totalService: number;
  totalOtherService: number;
  totalOperators: number;
  totalInteres: number;
  period: string;
  invoices: any;
}
// REGISTRAR PAGO

export interface ReqPaymentCotasPostPago {
  deudaPostpago: DeudaPostpago;
  infotransaccion: Infotransaccion;
}

export interface DeudaPostpago {
  IdDeudaPostPago: string;
  NroContrato: string;
  Periodo: string;
  TotalServicio: number;
  TotalOtrosServicios: number;
  TotalOperadores: number;
  TotalIntereses: number;
  TotalDeudaPostpago: number;
}

export interface Infotransaccion {
  MedioTransaccion: string;
  idReferenciaInterno: string;
  idReferenciaExterno: string;
}

export interface ResponseCotasRegisterPayment {
  NroTransaccion: string;
  IdDeudaPostPago: string;
  NroFactura: string;
  MontoPagado: number;
  Observacion: string;
}
